plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.SmartMosque331'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.SmartMosque331'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures{
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.work.runtime
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.android.volley:volley:1.2.1'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.android.volley:volley:1.2.1'

    // Add the Adhan library
    implementation 'com.batoulapps.adhan:adhan2:0.0.5'

    // Add core library desugaring
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
